server:
  port: 8888
spring:
  application:
    name: gateway-auth
  cloud:
    nacos:
      discovery:
        server-addr: 47.95.232.196:8847
        namespace: public
#    sentinel:
#      transport:
#        dashboard: 127.0.0.1:8858
#        #默认是将链路收敛   需要将链路收敛关闭
#      web-context-unify: false

    gateway:
      discovery:
        locator:
          enabled: true
      enabled: true
      routes:
      - id: exam-auth
        uri: lb://exam-auth
        predicates:
        - Path=/oauth/**,/user/**
      - id: exam-stu
        uri: lb://exam-stu
        predicates:
        - Path=/exam/**,/paper/**,/papers/**
      - id: exam-sup
        uri: lb://exam-sup
        predicates:
        - Path=/sup/**
      - id: exam-manages
        uri: lb://exam-manages
        predicates:
        - Path=/manages/**,/test/**
exam:
  gateway:
    shouldSkipUrls:
    - /oauth/**
    - /sso/**