server:
  port: 8888
spring:
  application:
    name: gateway-auth
  cloud:
    nacos:
      discovery:
        server-addr: 47.95.232.196:8847
        namespace: public

    gateway:
      discovery:
        locator:
          enabled: true
      enabled: true
      routes:
      - id: exam-auth
        uri: lb://exam-auth
        predicates:
        - Path=/oauth/**,/user/**
      - id: exam-stu
        uri: lb://exam-stu
        predicates:
        - Path=/exam/**,/paper/**,/papers/**
      - id: exam-sup
        uri: lb://exam-sup
        predicates:
        - Path=/sup/**,
exam:
  gateway:
    shouldSkipUrls:
    - /oauth/**
    - /sso/**